redis:
  host: localhost
  port: 6379
  connectionName: bull-dashboard
#  sentinels:
#    - host: localhost
#      port: 26379
#  name: mymaster

queue:
  sharedConnection: true
  prefix: bull

# Announce the queues to be displayed
queues:
  - products
  - errors

server:
  host: 0.0.0.0
  port: 3015
  console: warn
  basePath: 'ux'
